#!/bin/bash
#SBATCH --job-name=pca_jobs.txt
#SBATCH --output=./pca_jobs.txt_err_out/jobs_%A_%a.out
#SBATCH --error=./pca_jobs.txt_err_out/jobs_%A_%a.err
#SBATCH --partition=shared
#SBATCH --mem-per-cpu=10G --cpus-per-task=1
#SBATCH --array=1-3%3


echo "**** Job starts ****"
date
module load R/4.3
perl /dcs04/lieber/statsgen/shizhong/scripts/jhpce3/job_batch.pl --jfile pca_jobs.txt --nrun 1 --n $SLURM_ARRAY_TASK_ID
echo "**** Job ends ****"
date
